### PR TITLE
Clone os-autoinst-common into os-autoinst-distri-example

### PR DESCRIPTION
**Pull request by d3flex**
Fixes: https://progress.opensuse.org/issues/138416

### CODE REVIEW

**Review by Martchus — CHANGES_REQUESTED** [review]
It doesn't look right to add these cache files.

**Comment by b10n1k** [comment]
> It doesn't look right to add these cache files.

fixed. i have no idea what happened in the previous commit

**Review by kalikiana — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Review by okurz — COMMENTED** [review]
Somehow it does not feel right to pull in much more content into this comparing to the minimal repo content already there from before. Maybe we should including the content using git submodules here nevertheless?

**Comment by foursixnine** [comment]
> Somehow it does not feel right to pull in much more content into this comparing to the minimal repo content already there from before. Maybe we should including the content using git submodules here nevertheless?

+1

**Comment by kalikiana** [comment]
> Somehow it does not feel right to pull in much more content into this comparing to the minimal repo content already there from before. Maybe we should including the content using git submodules here nevertheless?

I don't follow. This is the approach taken in other repos. [poo#138416](https://progress.opensuse.org/issues/138416) says in **AC1** `os-autoinst/os-autoinst-distri-example) inherits static checks from os-autoinst-common`. That's what this PR does.

**Comment by okurz** [comment]
> > Somehow it does not feel right to pull in much more content into this comparing to the minimal repo content already there from before. Maybe we should including the content using git submodules here nevertheless?
> 
> **git sub-repo** which is used here is the approach taken in other repos. [poo#138416](https://progress.opensuse.org/issues/138416) says in **AC1** `os-autoinst/os-autoinst-distri-example inherits static checks from os-autoinst-common`. That's what this PR does.

I know that and likely you know that I know that so I don't see the point of your comment

**Pull request merged**
